local t = require("luatest")
local localsettings = require("muuri.localsettings")

t.test("starts unconfigured and remembers member and band folder", function()
  local s = localsettings.new(localsettings.memory_backend())
  t.falsy(s:is_configured())
  t.eq(s:member(), nil)
  s:set_member("aino")
  t.falsy(s:is_configured())
  s:set_band_folder("/home/user/Band")
  t.truthy(s:is_configured())
  t.eq(s:member(), "aino")
  t.eq(s:band_folder(), "/home/user/Band")
end)

t.test("Finnish characters in a folder path survive", function()
  local s = localsettings.new(localsettings.memory_backend())
  s:set_band_folder("C:\\Käyttäjät\\Ääni\\Bändi")
  t.eq(s:band_folder(), "C:\\Käyttäjät\\Ääni\\Bändi")
end)

t.test("empty values count as not set, and clear forgets everything", function()
  local s = localsettings.new(localsettings.memory_backend({ member = "" }))
  t.eq(s:member(), nil)
  s:set_member("eero"); s:set_band_folder("/b")
  s:clear()
  t.falsy(s:is_configured())
end)

t.test("settings written by one instance are read by another on the same backend", function()
  local backend = localsettings.memory_backend()
  localsettings.new(backend):set_member("eero")
  t.eq(localsettings.new(backend):member(), "eero")
end)

t.test("REAPER backend stores in extended state (needs REAPER)", function()
  if not reaper then t.skip("not running inside REAPER") end
  local s = localsettings.new(localsettings.reaper_backend())
  s:set_member("testmember")
  t.eq(s:member(), "testmember")
  s:set_member(nil)
  t.eq(s:member(), nil)
end)
