local t = require("luatest")
local path = require("muuri.path")

t.test("join uses exactly one separator, for both styles", function()
  t.eq(path.join("/", "a", "b", "c"), "a/b/c")
  t.eq(path.join("\\", "a", "b", "c"), "a\\b\\c")
  t.eq(path.join("/", "a/", "/b"), "a/b")
  t.eq(path.join("\\", "C:\\band\\", "\\song"), "C:\\band\\song")
  t.eq(path.join("/", "/home/user", "y"), "/home/user/y")
  t.eq(path.join("/", "a", "", "b"), "a/b")
end)

t.test("normalize converts mixed separators", function()
  t.eq(path.normalize("a\\b/c", "/"), "a/b/c")
  t.eq(path.normalize("a/b\\c", "\\"), "a\\b\\c")
  t.eq(path.normalize("a//b\\\\c", "/"), "a/b/c")
  t.eq(path.normalize("\\\\server\\share\\x", "\\"), "\\\\server\\share\\x")
end)

t.test("native_sep is a single separator character", function()
  t.truthy(path.native_sep() == "/" or path.native_sep() == "\\")
end)

t.test("basename and dirname work with either separator", function()
  t.eq(path.basename("/a/b/c.wav"), "c.wav")
  t.eq(path.basename("C:\\a\\b\\c.wav"), "c.wav")
  t.eq(path.basename("/a/b/"), "b")
  t.eq(path.dirname("/a/b/c.wav"), "/a/b")
  t.eq(path.dirname("C:\\a\\b\\c.wav"), "C:\\a\\b")
  t.eq(path.dirname("file.wav"), "")
end)

t.test("relative returns nil outside the root and uses forward slashes", function()
  t.eq(path.relative("/band/song", "/band/song/media/a.wav"), "media/a.wav")
  t.eq(path.relative("C:\\band\\song", "C:\\band\\song\\media\\a.wav"), "media/a.wav")
  t.eq(path.relative("/band/song", "/band/song2/a.wav"), nil)
  t.eq(path.relative("/band/song", "/band/song"), nil)
  t.eq(path.relative("/band/song/", "/band/song/x"), "x")
end)

t.test("too_long checks the Windows limit", function()
  t.falsy(path.too_long(("a"):rep(200)))
  t.truthy(path.too_long(("a"):rep(260)))
  t.truthy(path.too_long(("a"):rep(30), 20))
end)
