local t = require("luatest")
local slug = require("bandcollab.slug")

t.test("Finnish letters become plain ASCII", function()
  t.eq(slug.slug("Yö: kuka? Minä"), "yo-kuka-mina")
  t.eq(slug.slug("Åland Ääniä"), "aland-aania")
end)

t.test("forbidden characters and repeats collapse into single hyphens", function()
  t.eq(slug.slug('a<b>c:"d"/e\\f|g?h*i'), "a-b-c-d-e-f-g-h-i")
  t.eq(slug.slug("  --Hello   World--  "), "hello-world")
end)

t.test("Windows-reserved names are made safe", function()
  t.eq(slug.slug("con"), "con-x")
  t.eq(slug.slug("CON"), "con-x")
  t.eq(slug.slug("Aux"), "aux-x")
  t.eq(slug.slug("COM1"), "com1-x")
  t.eq(slug.slug("lpt9"), "lpt9-x")
  t.eq(slug.slug("console"), "console")
end)

t.test("empty or symbol-only names become 'untitled'", function()
  t.eq(slug.slug(""), "untitled")
  t.eq(slug.slug("???"), "untitled")
  t.eq(slug.slug("日本語"), "untitled")
end)

t.test("length is capped without a trailing hyphen", function()
  local s = slug.slug(("word "):rep(30))
  t.truthy(#s <= slug.DEFAULT_MAX)
  t.falsy(s:sub(-1) == "-")
  t.eq(slug.slug("abcdefghij", 5), "abcde")
  t.eq(slug.slug("ab cd", 3), "ab")
end)

t.test("unique is case-insensitive and numbers duplicates", function()
  t.eq(slug.unique("song", {}), "song")
  t.eq(slug.unique("song", { song = true }), "song-2")
  t.eq(slug.unique("song", { Song = true }), "song-2")
  t.eq(slug.unique("song", { song = true, ["song-2"] = true, ["SONG-3"] = true }), "song-4")
end)

t.test("valid recognizes acceptable slugs", function()
  t.truthy(slug.valid("kappale-a"))
  t.truthy(slug.valid("r1"))
  t.falsy(slug.valid("Kappale"))
  t.falsy(slug.valid("con"))
  t.falsy(slug.valid("-x"))
  t.falsy(slug.valid("x-"))
  t.falsy(slug.valid(""))
  t.falsy(slug.valid("a b"))
  t.falsy(slug.valid("yö"))
end)

t.test("every slug produced from awkward inputs is valid", function()
  for _, name in ipairs({ "Yö: kuka? Minä", "con", "", "???", "A/B\\C", ("x"):rep(200), "NUL", "  ", "ä", "Song #1 (live)" }) do
    t.truthy(slug.valid(slug.slug(name)), "slug of " .. string.format("%q", name))
  end
end)
