-- English UI text. Keys are shared with strings/fi.lua (tests/strings_test.lua checks parity).
-- err.<code>.what says what happened, err.<code>.action suggests the one next step.
return {
  wizard = {
    location_master = "Producer",
    location_publications = "Publications",
    location_proposals = "Proposals",
  },
  log = {
    filename = "CHANGELOG.md",
    title = "{title} - change log",
    publication = "Publication",
    import = "Proposal imported",
    import_undone = "Import undone",
    fact_taken = "Taken in: {n} tracks ({role})",
    rehearsal = "Rehearsal received",
    attention = "NOTE",
    attention_structure = "The structure changed ({reasons}). Fetch the master and check your tracks.",
    reason_length = "length",
    reason_tempo = "tempo",
    reason_sections = "sections",
    tasks = "To do",
    fact_stems = "{n} groups published",
    fact_length = "Length: {time}",
    fact_replaced = "Replaced: {n} tracks ({role})",
    fact_sent = "Sent: {time}",
  },
  ui = {
    import = {
      title = "Proposals",
      empty = "No proposals are waiting.",
      arriving = "A proposal from {member} is still arriving.",
      row = "{member}: {title}   ({time})",
      outdated_tag = "older version r{n}",
      review = "Review",
      open_master = "Open the master of this song first, then review the proposal.",
      preview_title = "What will happen",
      replaced = "{label}: replaced ({b_tracks} tracks, {b_items} items -> {a_tracks} tracks, {a_items} items)",
      added = "{label}: added ({a_tracks} tracks, {a_items} items)",
      ignored = "{label}: ignored",
      versions = "Based on r{base}; the master is at r{current}.",
      tempo = "Tempo: master {m} BPM, proposal {p} BPM",
      length = "Length: master {m}, proposal {p}",
      note_summary = "Note for the log (you may edit it)",
      note_body = "More details",
      accept = "Take into the master",
      cancel = "Cancel",
      undo_button = "Undo the last import",
      undo_hint = "Restores the master as it was before {delivery} was taken in. Anything you did in the master since then is lost.",
      working = "Working: {step}",
      imported = "Taken into the master.",
      undone = "Import undone.",
    },
    picker = {
      title = "Your workspace",
      intro = "Pick a song. You get your own separate project where only your own tracks can be changed. The other players are there to listen to, but cannot be edited. Nothing in the master changes until you propose it.",
      create = "Create my workspace",
      open = "Open my workspace",
      closed = "closed",
      nothing = "The producer has not published anything yet.",
      arriving = "A publication is still arriving. Wait a moment for the files to finish syncing.",
      arriving_song = "Still arriving: {title}",
      working = "Working: {step}",
      ready = "Your workspace is ready.",
      you = "You are {name} ({roles}).",
    },
    sync = {
      title = "Synchronize",
      song = "Song: {title}   (you: {member})",
      based_on = "Your workspace is based on r{n}.",
      all_current = "Everything is up to date.",
      arriving = "A newer version is still arriving. Wait a moment for the files to finish syncing.",
      step1 = "Step 1: get the master",
      step1_hint = "Updates the other members' tracks. Your own tracks do not change.",
      step1_button = "Get the master",
      step2 = "Step 2: propose to the master",
      step2_hint = "The producer decides whether your work is taken in. Nothing changes in the master until then.",
      step2_wait = "Available after step 1.",
      step2_button = "Propose",
      note_summary = "Message to the producer (one line)",
      note_body = "More details (optional)",
      undo_button = "Restore the previous state",
      undo_hint = "Undoes the last update to r{n}. Anything you did since then is lost.",
      working = "Working: {step}",
      fetched = "You now have r{n} of the master.",
      structure_warning = "The structure changed ({reasons}). Your tracks may no longer line up, so check them against the new stems.",
      undone = "Restored: your workspace is as it was before the update.",
      sent = "Proposal sent.",
      proposal_pending = "Proposal sent {time}. The producer has not handled it yet.",
      proposal_accepted = "Proposal sent {time}. The producer has taken it in.",
      before_sending = "Before sending",
      fix_orphans = "Move them into my folder",
      confirm = "I understand, send anyway",
      closed = "This rehearsal cycle is closed. New proposals are no longer accepted.",
    },
    workspace = { reference_track = "Reference mix (whole band, muted)" },
    publish = {
      title = "Publish a version",
      song = "Song: {title}",
      next = "This will be revision r{n}.",
      last = "Latest revision: r{n}",
      first = "Nothing has been published yet.",
      note_summary = "Note to the band (one line)",
      note_body = "More details (optional)",
      tasks = "Requests",
      task_who = "For",
      task_text = "What is needed",
      add_task = "Add request",
      remove_task = "Remove request",
      button = "Publish",
      publishing = "Publishing: {step}",
      done = "Published r{n}.",
      structure_warning = "The structure changed since the last version. The log will tell the members.",
    },
    receive = {
      title = "Receive a rehearsal",
      staging = "Folder where the rehearsal was copied",
      pick_button = "Choose a file in it...",
      pick_title = "Choose any file in the rehearsal's folder",
      scan = "Find songs",
      no_songs = "No projects were found in that folder.",
      library = "Library",
      cycle = "Date of the rehearsal (year-month-day)",
      song_ok = "Ready to receive",
      song_copy_question = "Is this a copy of {title}?",
      song_is_copy = "Yes, it is a copy",
      song_skip = "Skip",
      receive_button = "Receive the selected songs",
      progress = "Copying {file}...",
      received = "Received: {title}",
      cycles = "Rehearsal cycles",
      cycle_open = "open",
      cycle_closed = "closed",
      close_cycle = "Close cycle",
    },
    wizard = {
      title = "Set up the band",
      band_name = "Band name",
      language = "Language",
      folder = "Band folder (a folder everyone can reach)",
      members = "Members",
      member_name = "Name",
      is_producer = "Producer",
      instrument = "Instrument",
      tracks = "Tracks",
      add_member = "Add member",
      add_instrument = "Add instrument",
      remove_member = "Remove member",
      remove_instrument = "Remove instrument",
      create = "Create band folder and template",
      problems = "Please fix these first:",
      done = "Done. The band folder is ready.",
    },
    firstrun = {
      title = "Welcome",
      step_folder = "Where is the band folder?",
      pick_hint = "Choose the file band.json inside the band folder.",
      pick_button = "Choose...",
      pick_title = "Choose band.json in the band folder",
      folder_chosen = "Band folder: {folder}",
      step_member = "Who are you?",
      confirm = "Continue",
      ready = "All set, {name}.",
    },
  },
  err = {
    already_imported = { what = "This proposal has already been taken in.", action = "Choose another proposal." },
    wrong_song = { what = "This proposal is for a different song than the one that is open.", action = "Open the master of the song the proposal is for." },
    nothing_to_import = { what = "This proposal contains nothing that belongs to its sender.", action = "Ask the member to send it again." },
    import_backup_failed = { what = "A backup of the master could not be made ({detail}), so nothing was changed.", action = "Check the disk space and that the folder can be written to." },
    import_failed = { what = "Taking the proposal in failed ({detail}). The master was left as it was.", action = "Try again, or ask the member to send it again." },
    nothing_to_undo_import = { what = "There is no import to undo.", action = "Only the last import can be undone." },
    import_outdated = { what = "The proposal was made against r{base}; the master is now at r{current}.", action = "The other tracks may have changed since; check that it still fits." },
    import_conflict = { what = "You changed {detail} in the master after the version this proposal was based on.", action = "Accepting will replace those changes. The import can be undone." },
    import_tempo = { what = "The tempo in this proposal differs from the master's.", action = "The member's timing may not match the band." },
    import_folder_missing = { what = "The master has no folder for {detail}.", action = "It will be added at the end of the project." },
    import_ignored_role = { what = "{detail} in this proposal does not belong to its sender and will be ignored.", action = "Nothing else needs to be done." },
    import_longer = { what = "The proposal is longer than the master ({detail}).", action = "Check the ending." },
    nothing_newer = { what = "There is no newer version from the band.", action = "You already have the latest one." },
    nothing_to_undo = { what = "There is nothing to restore.", action = "Only the last update can be undone." },
    fetch_failed = { what = "Getting the latest version failed ({detail}). Your workspace was put back as it was.", action = "Try again in a moment." },
    preflight_failed = { what = "Your work cannot be sent yet.", action = "Fix the problems listed and try again." },
    preflight_needs_ack = { what = "Please look at the notes before sending.", action = "Confirm them, or fix them first." },
    send_orphans = { what = "{detail} track(s) are outside your folder.", action = "Move them into your folder, or delete them." },
    send_empty = { what = "Your folder is empty.", action = "Record something first, or confirm that you meant to send it empty." },
    send_timing = { what = "The tempo differs from the band's.", action = "Your timing may not match the band. Undo the tempo change, or send anyway." },
    send_unchanged = { what = "Nothing has changed since you last sent your work.", action = "Change something first, or send again anyway." },
    send_media_outside = { what = "{detail} audio file(s) were outside your workspace.", action = "They were copied into your delivery. Nothing else is needed." },
    workspace_exists = { what = "You already have a workspace for this song.", action = "Open it instead of making a new one." },
    workspace_missing = { what = "There is no workspace for this song yet.", action = "Create your own workspace first." },
    project_unsaved = { what = "The project has unsaved changes.", action = "Save the project first, then publish." },
    not_a_song = { what = "This project has not been received into the band folder.", action = "Receive the rehearsal first, then open the song from the band folder." },
    no_role_folders = { what = "The project has no role folders.", action = "Create the song from the band template." },
    render_failed = { what = "The audio for {detail} could not be rendered.", action = "Check the render settings and disk space, then try again." },
    publish_cannot_write = { what = "The publication could not be written ({detail}).", action = "Check that the band folder can be written to and try again." },
    revision_complete = { what = "This revision is already finished and cannot be changed.", action = "Publish again to make a new revision." },
    not_producer = { what = "Only the producer can receive rehearsals.", action = "Ask the producer to do this." },
    cycle_closed = { what = "The rehearsal cycle {detail} is closed.", action = "New proposals are no longer accepted for it. Ask the producer if something is missing." },
    cycle_unknown = { what = "There is no cycle for that date.", action = "Check the date." },
    registry_invalid = { what = "The band's song list is damaged.", action = "Restore it from the latest copy, or ask for help." },
    incomplete = { what = "This song did not arrive completely.", action = "Copy the project again from the recording computer." },
    already_registered = { what = "The song {detail} is already in the band folder.", action = "There is nothing to receive." },
    already_received = { what = "This exact project was already received as {detail}.", action = "Choose another project." },
    copy_undecided = { what = "This looks like a copy of {detail}.", action = "Say whether it is a copy of that song." },
    bad_date = { what = "The date {detail} is not valid.", action = "Write the date as year-month-day, for example 2026-09-29." },
    unknown_library = { what = "The library {detail} does not exist.", action = "Choose one of the band's libraries." },
    cannot_copy = { what = "The song could not be copied ({detail}).", action = "Check that there is enough disk space and try again." },
    cannot_write = { what = "The band folder could not be written to ({detail}).", action = "Check that the folder exists and can be written to." },
    empty_file = { what = "The file {path} is empty.", action = "Copy the project again from the recording computer." },
    truncated_file = { what = "The file {path} was cut short.", action = "Copy the project again from the recording computer." },
    firstrun_unknown_member = { what = "You are not in this band's member list.", action = "Choose your name from the list, or ask the producer to add you." },
    firstrun_needed = { what = "This computer has not been set up yet.", action = "Answer the two questions to get started." },
    wizard_no_band_name = { what = "The band has no name yet.", action = "Type the band's name." },
    wizard_no_members = { what = "There are no members yet.", action = "Add at least one member." },
    wizard_member_no_name = { what = "Member {member} has no name.", action = "Type the member's name." },
    wizard_duplicate_member = { what = "There are two members called {detail}.", action = "Give one of them a different name." },
    wizard_member_no_instrument = { what = "{detail} has no instrument.", action = "Add an instrument for {detail}." },
    wizard_instrument_no_label = { what = "An instrument of {detail} has no name.", action = "Type the instrument's name." },
    wizard_bad_tracks = { what = "The number of tracks for {detail} is not valid.", action = "Use a number from 1 to 32." },
    wizard_cannot_create = { what = "The band folder could not be set up ({detail}).", action = "Check that the folder exists and can be written to." },
    missing_marker = { what = "This pack is not complete yet.", action = "Wait a moment for the files to finish arriving, then try again." },
    bad_manifest = { what = "The pack's file list is damaged.", action = "Ask for the pack to be sent again." },
    marker_mismatch = { what = "The pack was changed after it was finished.", action = "Ask for the pack to be sent again." },
    missing_file = { what = "The file {path} is missing.", action = "Wait for the files to finish arriving, or ask for the pack to be sent again." },
    size_mismatch = { what = "The file {path} is incomplete.", action = "Wait for the file to finish arriving, then try again." },
    hash_mismatch = { what = "The file {path} is damaged.", action = "Ask for the pack to be sent again." },
    unreadable_file = { what = "The file {path} could not be read.", action = "Check that the file is kept on this computer and try again." },
    band_unreadable = { what = "The band settings could not be found.", action = "Check that you chose the right band folder." },
    band_invalid = { what = "The band settings file has a problem ({detail}).", action = "Ask the producer to fix the band settings." },
    band_too_new = { what = "The band settings were made with a newer version of this tool.", action = "Update the tool and try again." },
  },
}
