-- English UI text. Keys are shared with strings/fi.lua (tests/strings_test.lua checks parity).
-- err.<code>.what says what happened, err.<code>.action suggests the one next step.
return {
  wizard = {
    location_master = "Producer",
    location_publications = "Publications",
    location_proposals = "Proposals",
  },
  log = {
    filename = "CHANGELOG.md",
    title = "{title} - change log",
    publication = "Publication",
    import = "Proposal imported",
    rehearsal = "Rehearsal received",
    attention = "NOTE",
    attention_structure = "The structure changed ({reasons}). Fetch the master and check your tracks.",
    reason_length = "length",
    reason_tempo = "tempo",
    reason_sections = "sections",
    tasks = "To do",
    fact_stems = "{n} groups published",
    fact_length = "Length: {time}",
    fact_replaced = "Replaced: {n} tracks ({role})",
    fact_sent = "Sent: {time}",
  },
  ui = {
    publish = {
      title = "Publish a version",
      song = "Song: {title}",
      next = "This will be revision r{n}.",
      last = "Latest revision: r{n}",
      first = "Nothing has been published yet.",
      note_summary = "Note to the band (one line)",
      note_body = "More details (optional)",
      tasks = "Requests",
      task_who = "For",
      task_text = "What is needed",
      add_task = "Add request",
      remove_task = "Remove request",
      button = "Publish",
      publishing = "Publishing: {step}",
      done = "Published r{n}.",
      structure_warning = "The structure changed since the last version. The log will tell the members.",
    },
    receive = {
      title = "Receive a rehearsal",
      staging = "Folder where the rehearsal was copied",
      pick_button = "Choose a file in it...",
      pick_title = "Choose any file in the rehearsal's folder",
      scan = "Find songs",
      no_songs = "No projects were found in that folder.",
      library = "Library",
      cycle = "Date of the rehearsal (year-month-day)",
      song_ok = "Ready to receive",
      song_copy_question = "Is this a copy of {title}?",
      song_is_copy = "Yes, it is a copy",
      song_skip = "Skip",
      receive_button = "Receive the selected songs",
      progress = "Copying {file}...",
      received = "Received: {title}",
      cycles = "Rehearsal cycles",
      cycle_open = "open",
      cycle_closed = "closed",
      close_cycle = "Close cycle",
    },
    wizard = {
      title = "Set up the band",
      band_name = "Band name",
      language = "Language",
      folder = "Band folder (a folder everyone can reach)",
      members = "Members",
      member_name = "Name",
      is_producer = "Producer",
      instrument = "Instrument",
      tracks = "Tracks",
      add_member = "Add member",
      add_instrument = "Add instrument",
      remove_member = "Remove member",
      remove_instrument = "Remove instrument",
      create = "Create band folder and template",
      problems = "Please fix these first:",
      done = "Done. The band folder is ready.",
    },
    firstrun = {
      title = "Welcome",
      step_folder = "Where is the band folder?",
      pick_hint = "Choose the file band.json inside the band folder.",
      pick_button = "Choose...",
      pick_title = "Choose band.json in the band folder",
      folder_chosen = "Band folder: {folder}",
      step_member = "Who are you?",
      confirm = "Continue",
      ready = "All set, {name}.",
    },
  },
  err = {
    project_unsaved = { what = "The project has unsaved changes.", action = "Save the project first, then publish." },
    not_a_song = { what = "This project has not been received into the band folder.", action = "Receive the rehearsal first, then open the song from the band folder." },
    no_role_folders = { what = "The project has no role folders.", action = "Create the song from the band template." },
    render_failed = { what = "The audio for {detail} could not be rendered.", action = "Check the render settings and disk space, then try again." },
    publish_cannot_write = { what = "The publication could not be written ({detail}).", action = "Check that the band folder can be written to and try again." },
    revision_complete = { what = "This revision is already finished and cannot be changed.", action = "Publish again to make a new revision." },
    not_producer = { what = "Only the producer can receive rehearsals.", action = "Ask the producer to do this." },
    cycle_closed = { what = "The rehearsal cycle {detail} is closed.", action = "New proposals are no longer accepted for it. Ask the producer if something is missing." },
    cycle_unknown = { what = "There is no cycle for that date.", action = "Check the date." },
    registry_invalid = { what = "The band's song list is damaged.", action = "Restore it from the latest copy, or ask for help." },
    incomplete = { what = "This song did not arrive completely.", action = "Copy the project again from the recording computer." },
    already_registered = { what = "The song {detail} is already in the band folder.", action = "There is nothing to receive." },
    already_received = { what = "This exact project was already received as {detail}.", action = "Choose another project." },
    copy_undecided = { what = "This looks like a copy of {detail}.", action = "Say whether it is a copy of that song." },
    bad_date = { what = "The date {detail} is not valid.", action = "Write the date as year-month-day, for example 2026-09-29." },
    unknown_library = { what = "The library {detail} does not exist.", action = "Choose one of the band's libraries." },
    cannot_copy = { what = "The song could not be copied ({detail}).", action = "Check that there is enough disk space and try again." },
    cannot_write = { what = "The band folder could not be written to ({detail}).", action = "Check that the folder exists and can be written to." },
    empty_file = { what = "The file {path} is empty.", action = "Copy the project again from the recording computer." },
    truncated_file = { what = "The file {path} was cut short.", action = "Copy the project again from the recording computer." },
    firstrun_unknown_member = { what = "You are not in this band's member list.", action = "Choose your name from the list, or ask the producer to add you." },
    firstrun_needed = { what = "This computer has not been set up yet.", action = "Answer the two questions to get started." },
    wizard_no_band_name = { what = "The band has no name yet.", action = "Type the band's name." },
    wizard_no_members = { what = "There are no members yet.", action = "Add at least one member." },
    wizard_member_no_name = { what = "Member {member} has no name.", action = "Type the member's name." },
    wizard_duplicate_member = { what = "There are two members called {detail}.", action = "Give one of them a different name." },
    wizard_member_no_instrument = { what = "{detail} has no instrument.", action = "Add an instrument for {detail}." },
    wizard_instrument_no_label = { what = "An instrument of {detail} has no name.", action = "Type the instrument's name." },
    wizard_bad_tracks = { what = "The number of tracks for {detail} is not valid.", action = "Use a number from 1 to 32." },
    wizard_cannot_create = { what = "The band folder could not be set up ({detail}).", action = "Check that the folder exists and can be written to." },
    missing_marker = { what = "This pack is not complete yet.", action = "Wait a moment for the files to finish arriving, then try again." },
    bad_manifest = { what = "The pack's file list is damaged.", action = "Ask for the pack to be sent again." },
    marker_mismatch = { what = "The pack was changed after it was finished.", action = "Ask for the pack to be sent again." },
    missing_file = { what = "The file {path} is missing.", action = "Wait for the files to finish arriving, or ask for the pack to be sent again." },
    size_mismatch = { what = "The file {path} is incomplete.", action = "Wait for the file to finish arriving, then try again." },
    hash_mismatch = { what = "The file {path} is damaged.", action = "Ask for the pack to be sent again." },
    unreadable_file = { what = "The file {path} could not be read.", action = "Check that the file is kept on this computer and try again." },
    band_unreadable = { what = "The band settings could not be found.", action = "Check that you chose the right band folder." },
    band_invalid = { what = "The band settings file has a problem ({detail}).", action = "Ask the producer to fix the band settings." },
    band_too_new = { what = "The band settings were made with a newer version of this tool.", action = "Update the tool and try again." },
  },
}
