-- Suomenkielinen käyttöliittymäteksti. Avaimet ovat samat kuin tiedostossa strings/en.lua.
-- err.<koodi>.what kertoo mitä tapahtui, err.<koodi>.action ehdottaa yhden seuraavan askeleen.
return {
  wizard = {
    location_master = "Tuottaja",
    location_publications = "Julkaisut",
    location_proposals = "Ehdotukset",
  },
  ui = {
    receive = {
      title = "Ota harjoitus vastaan",
      staging = "Kansio, johon harjoitus on kopioitu",
      pick_button = "Valitse kansiosta tiedosto...",
      pick_title = "Valitse mikä tahansa tiedosto harjoituksen kansiosta",
      scan = "Etsi kappaleet",
      no_songs = "Kansiosta ei löytynyt projekteja.",
      library = "Kirjasto",
      cycle = "Harjoituksen päivämäärä (vuosi-kuukausi-päivä)",
      song_ok = "Valmis vastaanotettavaksi",
      song_copy_question = "Onko tämä kopio kappaleesta {title}?",
      song_is_copy = "Kyllä, se on kopio",
      song_skip = "Ohita",
      receive_button = "Ota valitut kappaleet vastaan",
      progress = "Kopioidaan: {file}...",
      received = "Vastaanotettu: {title}",
      cycles = "Harjoituskierrokset",
      cycle_open = "avoin",
      cycle_closed = "suljettu",
      close_cycle = "Sulje kierros",
    },
    wizard = {
      title = "Bändin asetukset",
      band_name = "Bändin nimi",
      language = "Kieli",
      folder = "Bändikansio (kansio, johon kaikilla on pääsy)",
      members = "Jäsenet",
      member_name = "Nimi",
      is_producer = "Tuottaja",
      instrument = "Soitin",
      tracks = "Raitoja",
      add_member = "Lisää jäsen",
      add_instrument = "Lisää soitin",
      remove_member = "Poista jäsen",
      remove_instrument = "Poista soitin",
      create = "Luo bändikansio ja pohja",
      problems = "Korjaa nämä ensin:",
      done = "Valmis. Bändikansio on luotu.",
    },
    firstrun = {
      title = "Tervetuloa",
      step_folder = "Missä bändikansio on?",
      pick_hint = "Valitse bändikansiosta tiedosto band.json.",
      pick_button = "Valitse...",
      pick_title = "Valitse bändikansiosta tiedosto band.json",
      folder_chosen = "Bändikansio: {folder}",
      step_member = "Kuka sinä olet?",
      confirm = "Jatka",
      ready = "Valmista, {name}.",
    },
  },
  err = {
    not_producer = { what = "Vain tuottaja voi ottaa harjoituksia vastaan.", action = "Pyydä tuottajaa tekemään tämä." },
    cycle_closed = { what = "Harjoituskierros {detail} on suljettu.", action = "Uusia ehdotuksia ei enää oteta vastaan. Kysy tuottajalta, jos jotain puuttuu." },
    cycle_unknown = { what = "Tälle päivälle ei ole harjoituskierrosta.", action = "Tarkista päivämäärä." },
    registry_invalid = { what = "Bändin kappaleluettelo on vioittunut.", action = "Palauta se viimeisimmästä kopiosta tai pyydä apua." },
    incomplete = { what = "Tämä kappale ei tullut perille kokonaan.", action = "Kopioi projekti uudelleen nauhoitustietokoneelta." },
    already_registered = { what = "Kappale {detail} on jo bändikansiossa.", action = "Vastaanotettavaa ei ole." },
    already_received = { what = "Täsmälleen tämä projekti on jo otettu vastaan nimellä {detail}.", action = "Valitse toinen projekti." },
    copy_undecided = { what = "Tämä näyttää kappaleen {detail} kopiolta.", action = "Kerro, onko se kopio tuosta kappaleesta." },
    bad_date = { what = "Päivämäärä {detail} ei kelpaa.", action = "Kirjoita päivämäärä muodossa vuosi-kuukausi-päivä, esimerkiksi 2026-09-29." },
    unknown_library = { what = "Kirjastoa {detail} ei ole.", action = "Valitse jokin bändin kirjastoista." },
    cannot_copy = { what = "Kappaletta ei voitu kopioida ({detail}).", action = "Tarkista, että levyllä on tilaa, ja yritä uudelleen." },
    cannot_write = { what = "Bändikansioon ei voitu kirjoittaa ({detail}).", action = "Tarkista, että kansio on olemassa ja siihen voi kirjoittaa." },
    empty_file = { what = "Tiedosto {path} on tyhjä.", action = "Kopioi projekti uudelleen nauhoitustietokoneelta." },
    truncated_file = { what = "Tiedosto {path} on katkennut kesken.", action = "Kopioi projekti uudelleen nauhoitustietokoneelta." },
    firstrun_unknown_member = { what = "Et ole tämän bändin jäsenluettelossa.", action = "Valitse nimesi luettelosta tai pyydä tuottajaa lisäämään sinut." },
    firstrun_needed = { what = "Tätä tietokonetta ei ole vielä otettu käyttöön.", action = "Vastaa kahteen kysymykseen, niin pääset alkuun." },
    wizard_no_band_name = { what = "Bändillä ei ole vielä nimeä.", action = "Kirjoita bändin nimi." },
    wizard_no_members = { what = "Jäseniä ei ole vielä lisätty.", action = "Lisää vähintään yksi jäsen." },
    wizard_member_no_name = { what = "Jäsenellä {member} ei ole nimeä.", action = "Kirjoita jäsenen nimi." },
    wizard_duplicate_member = { what = "Kaksi jäsentä on nimeltä {detail}.", action = "Anna toiselle eri nimi." },
    wizard_member_no_instrument = { what = "Jäsenellä {detail} ei ole soitinta.", action = "Lisää soitin jäsenelle {detail}." },
    wizard_instrument_no_label = { what = "Jäsenen {detail} yhdellä soittimella ei ole nimeä.", action = "Kirjoita soittimen nimi." },
    wizard_bad_tracks = { what = "Raitojen määrä soittimelle {detail} ei kelpaa.", action = "Käytä lukua 1-32." },
    wizard_cannot_create = { what = "Bändikansiota ei voitu valmistella ({detail}).", action = "Tarkista, että kansio on olemassa ja siihen voi kirjoittaa." },
    missing_marker = { what = "Tämä paketti ei ole vielä valmis.", action = "Odota hetki, että tiedostot ehtivät perille, ja yritä uudelleen." },
    bad_manifest = { what = "Paketin tiedostoluettelo on vioittunut.", action = "Pyydä lähettämään paketti uudelleen." },
    marker_mismatch = { what = "Pakettia on muutettu sen valmistumisen jälkeen.", action = "Pyydä lähettämään paketti uudelleen." },
    missing_file = { what = "Tiedosto {path} puuttuu.", action = "Odota, että tiedostot ehtivät perille, tai pyydä lähettämään paketti uudelleen." },
    size_mismatch = { what = "Tiedosto {path} on keskeneräinen.", action = "Odota, että tiedosto ehtii perille, ja yritä uudelleen." },
    hash_mismatch = { what = "Tiedosto {path} on vioittunut.", action = "Pyydä lähettämään paketti uudelleen." },
    unreadable_file = { what = "Tiedostoa {path} ei voitu lukea.", action = "Tarkista, että tiedosto on tallessa tässä tietokoneessa, ja yritä uudelleen." },
    band_unreadable = { what = "Bändin asetuksia ei löytynyt.", action = "Tarkista, että valitsit oikean bändikansion." },
    band_invalid = { what = "Bändin asetustiedostossa on virhe ({detail}).", action = "Pyydä tuottajaa korjaamaan bändin asetukset." },
    band_too_new = { what = "Bändin asetukset on tehty tämän työkalun uudemmalla versiolla.", action = "Päivitä työkalu ja yritä uudelleen." },
  },
}
