-- Suomenkielinen käyttöliittymäteksti. Avaimet ovat samat kuin tiedostossa strings/en.lua.
-- err.<koodi>.what kertoo mitä tapahtui, err.<koodi>.action ehdottaa yhden seuraavan askeleen.
return {
  wizard = {
    location_master = "Tuottaja",
    location_publications = "Julkaisut",
    location_proposals = "Ehdotukset",
  },
  log = {
    filename = "MUUTOSLOKI.md",
    title = "{title} - muutosloki",
    publication = "Julkaisu",
    import = "Ehdotus tuotu",
    rehearsal = "Harjoitus vastaanotettu",
    attention = "HUOM",
    attention_structure = "Rakenne muuttui ({reasons}). Hae pääversio ja tarkista omat raidat.",
    reason_length = "pituus",
    reason_tempo = "tempo",
    reason_sections = "osiot",
    tasks = "Tehtävää",
    fact_stems = "{n} ryhmää julkaistu",
    fact_length = "Pituus: {time}",
    fact_replaced = "Korvattu: {n} raitaa ({role})",
    fact_sent = "Lähetetty: {time}",
  },
  ui = {
    picker = {
      title = "Oma työtila",
      intro = "Valitse kappale. Saat oman erillisen projektin, jossa vain omia raitojasi voi muokata. Muut soittajat kuuluvat mukana, mutta niitä ei voi muuttaa. Pääversioon ei koske mikään ennen kuin ehdotat.",
      create = "Luo oma työtila",
      open = "Avaa oma työtila",
      closed = "suljettu",
      nothing = "Tuottaja ei ole vielä julkaissut mitään.",
      arriving = "Julkaisu on vielä tulossa. Odota hetki, että tiedostot ehtivät perille.",
      arriving_song = "Vielä tulossa: {title}",
      working = "Työn alla: {step}",
      ready = "Oma työtila on valmis.",
      you = "Sinä olet {name} ({roles}).",
    },
    sync = {
      title = "Synkronoi",
      song = "Kappale: {title}   (sinä: {member})",
      based_on = "Työtilasi perustuu versioon r{n}.",
      all_current = "Kaikki on ajan tasalla.",
      arriving = "Uudempi versio on vielä tulossa. Odota hetki, että tiedostot ehtivät perille.",
      step1 = "Vaihe 1: hae pääversio",
      step1_hint = "Päivittää muiden soittajien raidat. Omat raitasi eivät muutu.",
      step1_button = "Hae pääversio",
      step2 = "Vaihe 2: ehdota pääversioon",
      step2_hint = "Tuottaja päättää, otetaanko työsi mukaan. Pääversioon ei muutu mikään ennen sitä.",
      step2_wait = "Avautuu, kun vaihe 1 on tehty.",
      step2_button = "Ehdota",
      note_summary = "Viesti tuottajalle (yksi rivi)",
      note_body = "Lisätietoja (vapaaehtoinen)",
      undo_button = "Palauta edellinen tila",
      undo_hint = "Peruu viimeisimmän päivityksen versioon r{n}. Kaikki sen jälkeen tekemäsi menetetään.",
      working = "Työn alla: {step}",
      fetched = "Sinulla on nyt pääversion r{n}.",
      structure_warning = "Rakenne muuttui ({reasons}). Raitasi eivät ehkä enää osu kohdalleen, joten tarkista ne uusia raitoja vasten.",
      undone = "Palautettu: työtilasi on niin kuin ennen päivitystä.",
      sent = "Ehdotus lähetetty.",
      proposal_pending = "Ehdotus lähetetty {time}. Tuottaja ei ole vielä käsitellyt sitä.",
      proposal_accepted = "Ehdotus lähetetty {time}. Tuottaja on ottanut sen mukaan.",
      before_sending = "Ennen lähettämistä",
      fix_orphans = "Siirrä ne omaan kansiooni",
      confirm = "Ymmärrän, lähetä silti",
      closed = "Tämä harjoituskierros on suljettu. Uusia ehdotuksia ei enää oteta vastaan.",
    },
    workspace = { reference_track = "Referenssimiksaus (koko bändi, mykistetty)" },
    publish = {
      title = "Julkaise versio",
      song = "Kappale: {title}",
      next = "Tästä tulee versio r{n}.",
      last = "Viimeisin versio: r{n}",
      first = "Mitään ei ole vielä julkaistu.",
      note_summary = "Viesti bändille (yksi rivi)",
      note_body = "Lisätietoja (vapaaehtoinen)",
      tasks = "Pyynnöt",
      task_who = "Kenelle",
      task_text = "Mitä tarvitaan",
      add_task = "Lisää pyyntö",
      remove_task = "Poista pyyntö",
      button = "Julkaise",
      publishing = "Julkaistaan: {step}",
      done = "Julkaistu: r{n}.",
      structure_warning = "Rakenne on muuttunut edellisestä versiosta. Loki kertoo siitä jäsenille.",
    },
    receive = {
      title = "Ota harjoitus vastaan",
      staging = "Kansio, johon harjoitus on kopioitu",
      pick_button = "Valitse kansiosta tiedosto...",
      pick_title = "Valitse mikä tahansa tiedosto harjoituksen kansiosta",
      scan = "Etsi kappaleet",
      no_songs = "Kansiosta ei löytynyt projekteja.",
      library = "Kirjasto",
      cycle = "Harjoituksen päivämäärä (vuosi-kuukausi-päivä)",
      song_ok = "Valmis vastaanotettavaksi",
      song_copy_question = "Onko tämä kopio kappaleesta {title}?",
      song_is_copy = "Kyllä, se on kopio",
      song_skip = "Ohita",
      receive_button = "Ota valitut kappaleet vastaan",
      progress = "Kopioidaan: {file}...",
      received = "Vastaanotettu: {title}",
      cycles = "Harjoituskierrokset",
      cycle_open = "avoin",
      cycle_closed = "suljettu",
      close_cycle = "Sulje kierros",
    },
    wizard = {
      title = "Bändin asetukset",
      band_name = "Bändin nimi",
      language = "Kieli",
      folder = "Bändikansio (kansio, johon kaikilla on pääsy)",
      members = "Jäsenet",
      member_name = "Nimi",
      is_producer = "Tuottaja",
      instrument = "Soitin",
      tracks = "Raitoja",
      add_member = "Lisää jäsen",
      add_instrument = "Lisää soitin",
      remove_member = "Poista jäsen",
      remove_instrument = "Poista soitin",
      create = "Luo bändikansio ja pohja",
      problems = "Korjaa nämä ensin:",
      done = "Valmis. Bändikansio on luotu.",
    },
    firstrun = {
      title = "Tervetuloa",
      step_folder = "Missä bändikansio on?",
      pick_hint = "Valitse bändikansiosta tiedosto band.json.",
      pick_button = "Valitse...",
      pick_title = "Valitse bändikansiosta tiedosto band.json",
      folder_chosen = "Bändikansio: {folder}",
      step_member = "Kuka sinä olet?",
      confirm = "Jatka",
      ready = "Valmista, {name}.",
    },
  },
  err = {
    nothing_newer = { what = "Bändiltä ei ole uudempaa versiota.", action = "Sinulla on jo uusin." },
    nothing_to_undo = { what = "Palautettavaa ei ole.", action = "Vain viimeisimmän päivityksen voi peruuttaa." },
    fetch_failed = { what = "Uusimman version hakeminen epäonnistui ({detail}). Työtila palautettiin ennalleen.", action = "Yritä hetken kuluttua uudelleen." },
    preflight_failed = { what = "Työtäsi ei voi vielä lähettää.", action = "Korjaa luetellut asiat ja yritä uudelleen." },
    preflight_needs_ack = { what = "Katso huomautukset ennen lähettämistä.", action = "Vahvista ne tai korjaa ne ensin." },
    send_orphans = { what = "{detail} raitaa on oman kansiosi ulkopuolella.", action = "Siirrä ne omaan kansioosi tai poista ne." },
    send_empty = { what = "Kansiosi on tyhjä.", action = "Äänitä ensin jotain tai vahvista, että tarkoitit lähettää sen tyhjänä." },
    send_timing = { what = "Tempo poikkeaa bändin tempoista.", action = "Ajoituksesi ei ehkä sovi bändiin. Peru tempomuutos tai lähetä silti." },
    send_unchanged = { what = "Mikään ei ole muuttunut edellisen lähetyksen jälkeen.", action = "Muuta ensin jotain tai lähetä silti uudelleen." },
    send_media_outside = { what = "{detail} äänitiedostoa oli työtilasi ulkopuolella.", action = "Ne kopioitiin toimitukseen. Muuta ei tarvitse tehdä." },
    workspace_exists = { what = "Sinulla on jo oma työtila tälle kappaleelle.", action = "Avaa se uuden tekemisen sijaan." },
    workspace_missing = { what = "Tälle kappaleelle ei ole vielä omaa työtilaa.", action = "Luo ensin oma työtila." },
    project_unsaved = { what = "Projektissa on tallentamattomia muutoksia.", action = "Tallenna projekti ensin ja julkaise sitten." },
    not_a_song = { what = "Tätä projektia ei ole otettu vastaan bändikansioon.", action = "Ota harjoitus ensin vastaan ja avaa kappale bändikansiosta." },
    no_role_folders = { what = "Projektissa ei ole soitinkansioita.", action = "Luo kappale bändin pohjasta." },
    render_failed = { what = "Kohteen {detail} ääntä ei voitu renderöidä.", action = "Tarkista renderöinnin asetukset ja levytila ja yritä uudelleen." },
    publish_cannot_write = { what = "Julkaisua ei voitu kirjoittaa ({detail}).", action = "Tarkista, että bändikansioon voi kirjoittaa, ja yritä uudelleen." },
    revision_complete = { what = "Tämä versio on jo valmis eikä sitä voi muuttaa.", action = "Julkaise uudelleen, niin syntyy uusi versio." },
    not_producer = { what = "Vain tuottaja voi ottaa harjoituksia vastaan.", action = "Pyydä tuottajaa tekemään tämä." },
    cycle_closed = { what = "Harjoituskierros {detail} on suljettu.", action = "Uusia ehdotuksia ei enää oteta vastaan. Kysy tuottajalta, jos jotain puuttuu." },
    cycle_unknown = { what = "Tälle päivälle ei ole harjoituskierrosta.", action = "Tarkista päivämäärä." },
    registry_invalid = { what = "Bändin kappaleluettelo on vioittunut.", action = "Palauta se viimeisimmästä kopiosta tai pyydä apua." },
    incomplete = { what = "Tämä kappale ei tullut perille kokonaan.", action = "Kopioi projekti uudelleen nauhoitustietokoneelta." },
    already_registered = { what = "Kappale {detail} on jo bändikansiossa.", action = "Vastaanotettavaa ei ole." },
    already_received = { what = "Täsmälleen tämä projekti on jo otettu vastaan nimellä {detail}.", action = "Valitse toinen projekti." },
    copy_undecided = { what = "Tämä näyttää kappaleen {detail} kopiolta.", action = "Kerro, onko se kopio tuosta kappaleesta." },
    bad_date = { what = "Päivämäärä {detail} ei kelpaa.", action = "Kirjoita päivämäärä muodossa vuosi-kuukausi-päivä, esimerkiksi 2026-09-29." },
    unknown_library = { what = "Kirjastoa {detail} ei ole.", action = "Valitse jokin bändin kirjastoista." },
    cannot_copy = { what = "Kappaletta ei voitu kopioida ({detail}).", action = "Tarkista, että levyllä on tilaa, ja yritä uudelleen." },
    cannot_write = { what = "Bändikansioon ei voitu kirjoittaa ({detail}).", action = "Tarkista, että kansio on olemassa ja siihen voi kirjoittaa." },
    empty_file = { what = "Tiedosto {path} on tyhjä.", action = "Kopioi projekti uudelleen nauhoitustietokoneelta." },
    truncated_file = { what = "Tiedosto {path} on katkennut kesken.", action = "Kopioi projekti uudelleen nauhoitustietokoneelta." },
    firstrun_unknown_member = { what = "Et ole tämän bändin jäsenluettelossa.", action = "Valitse nimesi luettelosta tai pyydä tuottajaa lisäämään sinut." },
    firstrun_needed = { what = "Tätä tietokonetta ei ole vielä otettu käyttöön.", action = "Vastaa kahteen kysymykseen, niin pääset alkuun." },
    wizard_no_band_name = { what = "Bändillä ei ole vielä nimeä.", action = "Kirjoita bändin nimi." },
    wizard_no_members = { what = "Jäseniä ei ole vielä lisätty.", action = "Lisää vähintään yksi jäsen." },
    wizard_member_no_name = { what = "Jäsenellä {member} ei ole nimeä.", action = "Kirjoita jäsenen nimi." },
    wizard_duplicate_member = { what = "Kaksi jäsentä on nimeltä {detail}.", action = "Anna toiselle eri nimi." },
    wizard_member_no_instrument = { what = "Jäsenellä {detail} ei ole soitinta.", action = "Lisää soitin jäsenelle {detail}." },
    wizard_instrument_no_label = { what = "Jäsenen {detail} yhdellä soittimella ei ole nimeä.", action = "Kirjoita soittimen nimi." },
    wizard_bad_tracks = { what = "Raitojen määrä soittimelle {detail} ei kelpaa.", action = "Käytä lukua 1-32." },
    wizard_cannot_create = { what = "Bändikansiota ei voitu valmistella ({detail}).", action = "Tarkista, että kansio on olemassa ja siihen voi kirjoittaa." },
    missing_marker = { what = "Tämä paketti ei ole vielä valmis.", action = "Odota hetki, että tiedostot ehtivät perille, ja yritä uudelleen." },
    bad_manifest = { what = "Paketin tiedostoluettelo on vioittunut.", action = "Pyydä lähettämään paketti uudelleen." },
    marker_mismatch = { what = "Pakettia on muutettu sen valmistumisen jälkeen.", action = "Pyydä lähettämään paketti uudelleen." },
    missing_file = { what = "Tiedosto {path} puuttuu.", action = "Odota, että tiedostot ehtivät perille, tai pyydä lähettämään paketti uudelleen." },
    size_mismatch = { what = "Tiedosto {path} on keskeneräinen.", action = "Odota, että tiedosto ehtii perille, ja yritä uudelleen." },
    hash_mismatch = { what = "Tiedosto {path} on vioittunut.", action = "Pyydä lähettämään paketti uudelleen." },
    unreadable_file = { what = "Tiedostoa {path} ei voitu lukea.", action = "Tarkista, että tiedosto on tallessa tässä tietokoneessa, ja yritä uudelleen." },
    band_unreadable = { what = "Bändin asetuksia ei löytynyt.", action = "Tarkista, että valitsit oikean bändikansion." },
    band_invalid = { what = "Bändin asetustiedostossa on virhe ({detail}).", action = "Pyydä tuottajaa korjaamaan bändin asetukset." },
    band_too_new = { what = "Bändin asetukset on tehty tämän työkalun uudemmalla versiolla.", action = "Päivitä työkalu ja yritä uudelleen." },
  },
}
